services:
  mongodb-exporter:
    image: ${MONGODB_EXPORTER_IMAGE_REPOSITORY}:${MONGODB_EXPORTER_IMAGE_TAG}
    container_name: ${MONGODB_EXPORTER_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      - TZ

    env_file:
      - /run/secrets/mongodb-exporter.env

    ports:
      - "${MONGODB_EXPORTER_PORT}:9216"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

    networks:
      - traefik

networks:
  traefik:
    external: true
    name: ${MONGODB_EXPORTER_NETWORK}
