services:
  prometheus:
    image: ${PROMETHEUS_IMAGE_REPOSITORY}:${PROMETHEUS_IMAGE_TAG}
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    restart: unless-stopped
    init: true

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME}"

    expose:
      - "9090"

    environment:
      - TZ

    volumes:
      - "/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "/etc/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro"
      - "${PROMETHEUS_DATA_DIR}:/prometheus"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${PROMETHEUS_NETWORK}"
      - "traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_HOSTNAME}`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.entrypoints=${PROMETHEUS_ENTRYPOINTS}"
      - "traefik.http.routers.prometheus.tls=${PROMETHEUS_TLS}"

    networks:
      - traefik

networks:
  traefik:
    external: true
    name: ${PROMETHEUS_NETWORK}
