services:
  docker-socket-proxy:
    image: ${DOCKER_SOCKET_PROXY_IMAGE_REPOSITORY}:${DOCKER_SOCKET_PROXY_IMAGE_TAG}
    container_name: ${DOCKER_SOCKET_PROXY_CONTAINER_NAME}
    restart: unless-stopped

    ports:
      - "${DOCKER_SOCKET_PROXY_LISTEN_ADDRESS}:${DOCKER_SOCKET_PROXY_LISTEN_PORT}:2375"

    volumes:
      - "${DOCKER_SOCKET_PROXY_SOCKET_PATH}:/var/run/docker.sock:ro"

    environment:
      - CONTAINERS=${DOCKER_SOCKET_PROXY_CONTAINERS}
      - EVENTS=${DOCKER_SOCKET_PROXY_EVENTS}
      - IMAGES=${DOCKER_SOCKET_PROXY_IMAGES}
      - INFO=${DOCKER_SOCKET_PROXY_INFO}
      - NETWORKS=${DOCKER_SOCKET_PROXY_NETWORKS}
      - PING=${DOCKER_SOCKET_PROXY_PING}
      - VERSION=${DOCKER_SOCKET_PROXY_VERSION}
      - VOLUMES=${DOCKER_SOCKET_PROXY_VOLUMES}
      - POST=${DOCKER_SOCKET_PROXY_POST}
      - AUTH=${DOCKER_SOCKET_PROXY_AUTH}
      - SECRETS=${DOCKER_SOCKET_PROXY_SECRETS}
      - SERVICES=${DOCKER_SOCKET_PROXY_SERVICES}
      - SWARM=${DOCKER_SOCKET_PROXY_SWARM}
      - TASKS=${DOCKER_SOCKET_PROXY_TASKS}
