services:
  postgres-exporter:
    image: ${POSTGRES_EXPORTER_IMAGE_REPOSITORY}:${POSTGRES_EXPORTER_IMAGE_TAG}
    container_name: ${POSTGRES_EXPORTER_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      - TZ

    env_file:
      - /run/secrets/postgres-exporter.env

    ports:
      - "${POSTGRES_EXPORTER_PORT}:9187"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

    networks:
      - traefik

networks:
  traefik:
    external: true
    name: ${POSTGRES_EXPORTER_NETWORK}
